package com.events.domain;

public class ShortUrlBase {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shorturlbase.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shorturlbase.short_key
     *
     * @mbggenerated
     */
    private String shortKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shorturlbase.real_url
     *
     * @mbggenerated
     */
    private String realUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shorturlbase.comments
     *
     * @mbggenerated
     */
    private String comments;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shorturlbase.opaque
     *
     * @mbggenerated
     */
    private Short opaque;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shorturlbase.id
     *
     * @return the value of shorturlbase.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shorturlbase.id
     *
     * @param id the value for shorturlbase.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shorturlbase.short_key
     *
     * @return the value of shorturlbase.short_key
     *
     * @mbggenerated
     */
    public String getShortKey() {
        return shortKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shorturlbase.short_key
     *
     * @param shortKey the value for shorturlbase.short_key
     *
     * @mbggenerated
     */
    public void setShortKey(String shortKey) {
        this.shortKey = shortKey == null ? null : shortKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shorturlbase.real_url
     *
     * @return the value of shorturlbase.real_url
     *
     * @mbggenerated
     */
    public String getRealUrl() {
        return realUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shorturlbase.real_url
     *
     * @param realUrl the value for shorturlbase.real_url
     *
     * @mbggenerated
     */
    public void setRealUrl(String realUrl) {
        this.realUrl = realUrl == null ? null : realUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shorturlbase.comments
     *
     * @return the value of shorturlbase.comments
     *
     * @mbggenerated
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shorturlbase.comments
     *
     * @param comments the value for shorturlbase.comments
     *
     * @mbggenerated
     */
    public void setComments(String comments) {
        this.comments = comments == null ? null : comments.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shorturlbase.opaque
     *
     * @return the value of shorturlbase.opaque
     *
     * @mbggenerated
     */
    public Short getOpaque() {
        return opaque;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shorturlbase.opaque
     *
     * @param opaque the value for shorturlbase.opaque
     *
     * @mbggenerated
     */
    public void setOpaque(Short opaque) {
        this.opaque = opaque;
    }
}