package com.events.domain;

import java.math.BigDecimal;
import java.util.Date;

public class UserTransfer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_transfer.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_transfer.REQUEST_ID
     *
     * @mbggenerated
     */
    private String requestId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_transfer.CONTRACT_ADDRESS
     *
     * @mbggenerated
     */
    private String contractAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_transfer.PAYER
     *
     * @mbggenerated
     */
    private String payer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_transfer.RECEIVER
     *
     * @mbggenerated
     */
    private String receiver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_transfer.AMOUNT
     *
     * @mbggenerated
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_transfer.SIGN
     *
     * @mbggenerated
     */
    private String sign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_transfer.HASH_CODE
     *
     * @mbggenerated
     */
    private String hashCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_transfer.ROW_ADDTIME
     *
     * @mbggenerated
     */
    private Date rowAddtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_transfer.ROW_UPDATETIME
     *
     * @mbggenerated
     */
    private Date rowUpdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_transfer.ENV
     *
     * @mbggenerated
     */
    private String env;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_transfer.ID
     *
     * @return the value of user_transfer.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_transfer.ID
     *
     * @param id the value for user_transfer.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_transfer.REQUEST_ID
     *
     * @return the value of user_transfer.REQUEST_ID
     *
     * @mbggenerated
     */
    public String getRequestId() {
        return requestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_transfer.REQUEST_ID
     *
     * @param requestId the value for user_transfer.REQUEST_ID
     *
     * @mbggenerated
     */
    public void setRequestId(String requestId) {
        this.requestId = requestId == null ? null : requestId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_transfer.CONTRACT_ADDRESS
     *
     * @return the value of user_transfer.CONTRACT_ADDRESS
     *
     * @mbggenerated
     */
    public String getContractAddress() {
        return contractAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_transfer.CONTRACT_ADDRESS
     *
     * @param contractAddress the value for user_transfer.CONTRACT_ADDRESS
     *
     * @mbggenerated
     */
    public void setContractAddress(String contractAddress) {
        this.contractAddress = contractAddress == null ? null : contractAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_transfer.PAYER
     *
     * @return the value of user_transfer.PAYER
     *
     * @mbggenerated
     */
    public String getPayer() {
        return payer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_transfer.PAYER
     *
     * @param payer the value for user_transfer.PAYER
     *
     * @mbggenerated
     */
    public void setPayer(String payer) {
        this.payer = payer == null ? null : payer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_transfer.RECEIVER
     *
     * @return the value of user_transfer.RECEIVER
     *
     * @mbggenerated
     */
    public String getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_transfer.RECEIVER
     *
     * @param receiver the value for user_transfer.RECEIVER
     *
     * @mbggenerated
     */
    public void setReceiver(String receiver) {
        this.receiver = receiver == null ? null : receiver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_transfer.AMOUNT
     *
     * @return the value of user_transfer.AMOUNT
     *
     * @mbggenerated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_transfer.AMOUNT
     *
     * @param amount the value for user_transfer.AMOUNT
     *
     * @mbggenerated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_transfer.SIGN
     *
     * @return the value of user_transfer.SIGN
     *
     * @mbggenerated
     */
    public String getSign() {
        return sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_transfer.SIGN
     *
     * @param sign the value for user_transfer.SIGN
     *
     * @mbggenerated
     */
    public void setSign(String sign) {
        this.sign = sign == null ? null : sign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_transfer.HASH_CODE
     *
     * @return the value of user_transfer.HASH_CODE
     *
     * @mbggenerated
     */
    public String getHashCode() {
        return hashCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_transfer.HASH_CODE
     *
     * @param hashCode the value for user_transfer.HASH_CODE
     *
     * @mbggenerated
     */
    public void setHashCode(String hashCode) {
        this.hashCode = hashCode == null ? null : hashCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_transfer.ROW_ADDTIME
     *
     * @return the value of user_transfer.ROW_ADDTIME
     *
     * @mbggenerated
     */
    public Date getRowAddtime() {
        return rowAddtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_transfer.ROW_ADDTIME
     *
     * @param rowAddtime the value for user_transfer.ROW_ADDTIME
     *
     * @mbggenerated
     */
    public void setRowAddtime(Date rowAddtime) {
        this.rowAddtime = rowAddtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_transfer.ROW_UPDATETIME
     *
     * @return the value of user_transfer.ROW_UPDATETIME
     *
     * @mbggenerated
     */
    public Date getRowUpdatetime() {
        return rowUpdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_transfer.ROW_UPDATETIME
     *
     * @param rowUpdatetime the value for user_transfer.ROW_UPDATETIME
     *
     * @mbggenerated
     */
    public void setRowUpdatetime(Date rowUpdatetime) {
        this.rowUpdatetime = rowUpdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_transfer.ENV
     *
     * @return the value of user_transfer.ENV
     *
     * @mbggenerated
     */
    public String getEnv() {
        return env;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_transfer.ENV
     *
     * @param env the value for user_transfer.ENV
     *
     * @mbggenerated
     */
    public void setEnv(String env) {
        this.env = env == null ? null : env.trim();
    }
}