package com.shanhai.domain;

public class ContractWithBLOBs extends Contract {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.bytecode_bin
     *
     * @mbggenerated
     */
    private String bytecodeBin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.contract_abi
     *
     * @mbggenerated
     */
    private String contractAbi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.contract_bin
     *
     * @mbggenerated
     */
    private String contractBin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.contract_source
     *
     * @mbggenerated
     */
    private String contractSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.create_time
     *
     * @mbggenerated
     */
    private byte[] createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.deploy_time
     *
     * @mbggenerated
     */
    private byte[] deployTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.modify_time
     *
     * @mbggenerated
     */
    private byte[] modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.bytecode_bin
     *
     * @return the value of contract.bytecode_bin
     *
     * @mbggenerated
     */
    public String getBytecodeBin() {
        return bytecodeBin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.bytecode_bin
     *
     * @param bytecodeBin the value for contract.bytecode_bin
     *
     * @mbggenerated
     */
    public void setBytecodeBin(String bytecodeBin) {
        this.bytecodeBin = bytecodeBin == null ? null : bytecodeBin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.contract_abi
     *
     * @return the value of contract.contract_abi
     *
     * @mbggenerated
     */
    public String getContractAbi() {
        return contractAbi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.contract_abi
     *
     * @param contractAbi the value for contract.contract_abi
     *
     * @mbggenerated
     */
    public void setContractAbi(String contractAbi) {
        this.contractAbi = contractAbi == null ? null : contractAbi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.contract_bin
     *
     * @return the value of contract.contract_bin
     *
     * @mbggenerated
     */
    public String getContractBin() {
        return contractBin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.contract_bin
     *
     * @param contractBin the value for contract.contract_bin
     *
     * @mbggenerated
     */
    public void setContractBin(String contractBin) {
        this.contractBin = contractBin == null ? null : contractBin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.contract_source
     *
     * @return the value of contract.contract_source
     *
     * @mbggenerated
     */
    public String getContractSource() {
        return contractSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.contract_source
     *
     * @param contractSource the value for contract.contract_source
     *
     * @mbggenerated
     */
    public void setContractSource(String contractSource) {
        this.contractSource = contractSource == null ? null : contractSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.create_time
     *
     * @return the value of contract.create_time
     *
     * @mbggenerated
     */
    public byte[] getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.create_time
     *
     * @param createTime the value for contract.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(byte[] createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.deploy_time
     *
     * @return the value of contract.deploy_time
     *
     * @mbggenerated
     */
    public byte[] getDeployTime() {
        return deployTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.deploy_time
     *
     * @param deployTime the value for contract.deploy_time
     *
     * @mbggenerated
     */
    public void setDeployTime(byte[] deployTime) {
        this.deployTime = deployTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.modify_time
     *
     * @return the value of contract.modify_time
     *
     * @mbggenerated
     */
    public byte[] getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.modify_time
     *
     * @param modifyTime the value for contract.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(byte[] modifyTime) {
        this.modifyTime = modifyTime;
    }
}