package com.shanhai.domain;

public class KeyStoreInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column key_store_info.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column key_store_info.private_key
     *
     * @mbggenerated
     */
    private String privateKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column key_store_info.public_key
     *
     * @mbggenerated
     */
    private String publicKey;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column key_store_info.address
     *
     * @return the value of key_store_info.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column key_store_info.address
     *
     * @param address the value for key_store_info.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column key_store_info.private_key
     *
     * @return the value of key_store_info.private_key
     *
     * @mbggenerated
     */
    public String getPrivateKey() {
        return privateKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column key_store_info.private_key
     *
     * @param privateKey the value for key_store_info.private_key
     *
     * @mbggenerated
     */
    public void setPrivateKey(String privateKey) {
        this.privateKey = privateKey == null ? null : privateKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column key_store_info.public_key
     *
     * @return the value of key_store_info.public_key
     *
     * @mbggenerated
     */
    public String getPublicKey() {
        return publicKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column key_store_info.public_key
     *
     * @param publicKey the value for key_store_info.public_key
     *
     * @mbggenerated
     */
    public void setPublicKey(String publicKey) {
        this.publicKey = publicKey == null ? null : publicKey.trim();
    }
}