package com.shanhai.domain;

import java.math.BigDecimal;

public class Monitor {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor.block_height
     *
     * @mbggenerated
     */
    private BigDecimal blockHeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor.group_id
     *
     * @mbggenerated
     */
    private Integer groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor.pbft_view
     *
     * @mbggenerated
     */
    private BigDecimal pbftView;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor.pending_transaction_count
     *
     * @mbggenerated
     */
    private BigDecimal pendingTransactionCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitor.timestamp
     *
     * @mbggenerated
     */
    private Long timestamp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor.id
     *
     * @return the value of monitor.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor.id
     *
     * @param id the value for monitor.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor.block_height
     *
     * @return the value of monitor.block_height
     *
     * @mbggenerated
     */
    public BigDecimal getBlockHeight() {
        return blockHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor.block_height
     *
     * @param blockHeight the value for monitor.block_height
     *
     * @mbggenerated
     */
    public void setBlockHeight(BigDecimal blockHeight) {
        this.blockHeight = blockHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor.group_id
     *
     * @return the value of monitor.group_id
     *
     * @mbggenerated
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor.group_id
     *
     * @param groupId the value for monitor.group_id
     *
     * @mbggenerated
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor.pbft_view
     *
     * @return the value of monitor.pbft_view
     *
     * @mbggenerated
     */
    public BigDecimal getPbftView() {
        return pbftView;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor.pbft_view
     *
     * @param pbftView the value for monitor.pbft_view
     *
     * @mbggenerated
     */
    public void setPbftView(BigDecimal pbftView) {
        this.pbftView = pbftView;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor.pending_transaction_count
     *
     * @return the value of monitor.pending_transaction_count
     *
     * @mbggenerated
     */
    public BigDecimal getPendingTransactionCount() {
        return pendingTransactionCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor.pending_transaction_count
     *
     * @param pendingTransactionCount the value for monitor.pending_transaction_count
     *
     * @mbggenerated
     */
    public void setPendingTransactionCount(BigDecimal pendingTransactionCount) {
        this.pendingTransactionCount = pendingTransactionCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitor.timestamp
     *
     * @return the value of monitor.timestamp
     *
     * @mbggenerated
     */
    public Long getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitor.timestamp
     *
     * @param timestamp the value for monitor.timestamp
     *
     * @mbggenerated
     */
    public void setTimestamp(Long timestamp) {
        this.timestamp = timestamp;
    }
}