package com.shanhai.domain;

import java.math.BigDecimal;

public class Performance {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performance.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performance.cpu_use_ratio
     *
     * @mbggenerated
     */
    private BigDecimal cpuUseRatio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performance.disk_use_ratio
     *
     * @mbggenerated
     */
    private BigDecimal diskUseRatio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performance.memory_use_ratio
     *
     * @mbggenerated
     */
    private BigDecimal memoryUseRatio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performance.rxbps
     *
     * @mbggenerated
     */
    private BigDecimal rxbps;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performance.timestamp
     *
     * @mbggenerated
     */
    private Long timestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performance.txbps
     *
     * @mbggenerated
     */
    private BigDecimal txbps;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performance.id
     *
     * @return the value of performance.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performance.id
     *
     * @param id the value for performance.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performance.cpu_use_ratio
     *
     * @return the value of performance.cpu_use_ratio
     *
     * @mbggenerated
     */
    public BigDecimal getCpuUseRatio() {
        return cpuUseRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performance.cpu_use_ratio
     *
     * @param cpuUseRatio the value for performance.cpu_use_ratio
     *
     * @mbggenerated
     */
    public void setCpuUseRatio(BigDecimal cpuUseRatio) {
        this.cpuUseRatio = cpuUseRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performance.disk_use_ratio
     *
     * @return the value of performance.disk_use_ratio
     *
     * @mbggenerated
     */
    public BigDecimal getDiskUseRatio() {
        return diskUseRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performance.disk_use_ratio
     *
     * @param diskUseRatio the value for performance.disk_use_ratio
     *
     * @mbggenerated
     */
    public void setDiskUseRatio(BigDecimal diskUseRatio) {
        this.diskUseRatio = diskUseRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performance.memory_use_ratio
     *
     * @return the value of performance.memory_use_ratio
     *
     * @mbggenerated
     */
    public BigDecimal getMemoryUseRatio() {
        return memoryUseRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performance.memory_use_ratio
     *
     * @param memoryUseRatio the value for performance.memory_use_ratio
     *
     * @mbggenerated
     */
    public void setMemoryUseRatio(BigDecimal memoryUseRatio) {
        this.memoryUseRatio = memoryUseRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performance.rxbps
     *
     * @return the value of performance.rxbps
     *
     * @mbggenerated
     */
    public BigDecimal getRxbps() {
        return rxbps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performance.rxbps
     *
     * @param rxbps the value for performance.rxbps
     *
     * @mbggenerated
     */
    public void setRxbps(BigDecimal rxbps) {
        this.rxbps = rxbps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performance.timestamp
     *
     * @return the value of performance.timestamp
     *
     * @mbggenerated
     */
    public Long getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performance.timestamp
     *
     * @param timestamp the value for performance.timestamp
     *
     * @mbggenerated
     */
    public void setTimestamp(Long timestamp) {
        this.timestamp = timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performance.txbps
     *
     * @return the value of performance.txbps
     *
     * @mbggenerated
     */
    public BigDecimal getTxbps() {
        return txbps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performance.txbps
     *
     * @param txbps the value for performance.txbps
     *
     * @mbggenerated
     */
    public void setTxbps(BigDecimal txbps) {
        this.txbps = txbps;
    }
}