package com.shanhai.mapper;

import com.shanhai.domain.KeyStoreInfo;

public interface KeyStoreInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key_store_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String address);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key_store_info
     *
     * @mbggenerated
     */
    int insert(KeyStoreInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key_store_info
     *
     * @mbggenerated
     */
    int insertSelective(KeyStoreInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key_store_info
     *
     * @mbggenerated
     */
    KeyStoreInfo selectByPrimaryKey(String address);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key_store_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(KeyStoreInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key_store_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(KeyStoreInfo record);
}