package com.shanhai.mapper;

import com.shanhai.domain.Performance;

public interface PerformanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table performance
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table performance
     *
     * @mbggenerated
     */
    int insert(Performance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table performance
     *
     * @mbggenerated
     */
    int insertSelective(Performance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table performance
     *
     * @mbggenerated
     */
    Performance selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table performance
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Performance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table performance
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Performance record);
}