package com.events.mapper;

import com.events.domain.UserTransfer;

public interface UserTransferMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_transfer
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_transfer
     *
     * @mbggenerated
     */
    int insert(UserTransfer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_transfer
     *
     * @mbggenerated
     */
    int insertSelective(UserTransfer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_transfer
     *
     * @mbggenerated
     */
    UserTransfer selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_transfer
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserTransfer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_transfer
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserTransfer record);
}